version: '3.8'

services:
  ticktocktimerapp:
    build: .
    container_name: ticktocktimer
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - ticktock_network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - ticktock_network

networks:
  ticktock_network:
    driver: bridge

volumes:
  db_data:
